Entity/WeekProduction.php
<?php

namespace Smle\PanBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * WeekProduction
 *
 * @ORM\Table("pan_week_production")
 * @ORM\Entity(repositoryClass="Smle\PanBundle\Entity\WeekProductionRepository")
 */
class WeekProduction
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;

	/**
	 * @ORM\OneToMany(targetEntity="Smle\PanBundle\Entity\PanierOrderProductUnit", mappedBy="weekProduction", cascade={"persist", "remove"})
	 */
	private $productUnits;

	/**
	 * @var boolean
     * 
     * @ORM\Column(name="prevision", type="boolean", options={"default" : FALSE})
	 */
	private $prevision;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return WeekProduction
     */
    public function setDate($date)
    {
        $this->date = $date;
    
        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->productUnits = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Add productUnits
     *
     * @param \Smle\PanBundle\Entity\PanierOrderProductUnit $productUnits
     * @return WeekProduction
     */
    public function addProductUnit(\Smle\PanBundle\Entity\PanierOrderProductUnit $productUnits)
    {
        $this->productUnits[] = $productUnits;
    
        return $this;
    }

    /**
     * Remove productUnits
     *
     * @param \Smle\PanBundle\Entity\PanierOrderProductUnit $productUnits
     */
    public function removeProductUnit(\Smle\PanBundle\Entity\PanierOrderProductUnit $productUnits)
    {
        $this->productUnits->removeElement($productUnits);
    }

    /**
     * Get productUnits
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getProductUnits()
    {
        return $this->productUnits;
    }

    /**
     * Get total quantity
     *
     * @return float 
     */
    public function getTotalQuantities()
    {
        $total = 0;
        foreach ($this->getProductUnits() as $pu) $total += $pu->getQuantity();
        return $total;
    }

    /**
     * Set prevision
     *
     * @param boolean $prevision
     * @return WeekProduction
     */
    public function setPrevision($prevision)
    {
        $this->prevision = $prevision;
    
        return $this;
    }

    /**
     * Get prevision
     *
     * @return boolean 
     */
    public function getPrevision()
    {
        return $this->prevision;
    }

    /**
     * Get productUnit
     *
     * @return \Smle\PanBundle\Entity\PanierOrderProductUnit 
     */
    public function getProductUnit($id)
    {
        foreach ($this->getProductUnits() as $pu) {
            if( $pu->getProductPrice()->getId() == $id) return $pu;
        }
        return null;
    }
}

Form/WeekProductionType.php
<?php

namespace Smle\PanBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class WeekProductionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date')
            ->add('prevision')
            ->add('productUnits', 'collection', array(
                'type' => new PanierOrderProductUnitType(),
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => true
                ))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Smle\PanBundle\Entity\WeekProduction'
        ));
    }

    public function getName()
    {
        return 'smle_panbundle_weekproductiontype';
    }
}

Controller/WeekProductionController.php
<?php

namespace Smle\PanBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Smle\PanBundle\Entity\WeekProduction;
use Smle\PanBundle\Form\WeekProductionType;

use Smle\PanBundle\Form\PanierOrderProductUnitType;
use Smle\PanBundle\Entity\PanierOrderProductUnit;

use Symfony\Component\HttpFoundation\Response;

/**
 * WeekProduction controller.
 *
 */
class WeekProductionController extends Controller
{
    /**
     * Lists all WeekProduction entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('SmlePanBundle:WeekProduction')->findAll();

        return $this->render('SmlePanBundle:WeekProduction:index.html.twig', array(
            'entities' => $entities,
        ));
        /*
        return $this->dailyTypeAction('');
        */
    }

    /**
     * Finds and displays a WeekProduction entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SmlePanBundle:WeekProduction')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find WeekProduction entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('SmlePanBundle:WeekProduction:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),        ));
    }

    /**
     * Get current week
     *
     */
    private function getCurrentWeek($date)
    {
        if(!$date) {
            $date = new \DateTime('today');
            return $date->modify('-'.(($date->format('w') + 6) % 7).' Days');
        }
        return $date = new \DateTime($date);
    }

    /**
     * Return final weekProduction creation form.
     *
     */
    private function buildFinalCreationForm($entity, $twig)
    {
        $em = $this->getDoctrine()->getManager();

        $productPrices = $em->getRepository('SmlePanBundle:ProductPrice')->findCurrents($entity->getDate());

        if (!$productPrices) {
            throw $this->createNotFoundException('Unable to find ProductPrice entity.');
        }
        
        foreach($productPrices as $productPrice) {
            $panierOrderProductUnit = new PanierOrderProductUnit;
            $panierOrderProductUnit->setProductPrice($productPrice);
            $panierOrderProductUnit->setWeekProduction($entity);
            $entity->addProductUnit($panierOrderProductUnit);
        }

        $form = $this->createForm(new WeekProductionType(), $entity);

        return $this->render('SmlePanBundle:WeekProduction:'.$twig.'.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
            'productPrices' => $productPrices
        ));
    }

    /**
     * Displays a form to create a new WeekProduction entity.
     *
     */
    public function newAction($date)
    {
		$date = $this->getCurrentWeek($date);
		
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SmlePanBundle:WeekProduction')->findBy(array('date' => $date, 'prevision' => true));
        if($entity) {
            return $this->editAction($entity[0]->getId());
        }
        
        $entity = new WeekProduction();
        
        $entity->setDate($date);
        $entity->setPrevision(true);
        
        return $this->buildFinalCreationForm($entity, 'new');
    }

    /**
     * Creates a new WeekProduction entity.
     *
     */
    public function createAction(Request $request)
    {
        $entity  = new WeekProduction();
        
        $form = $this->createForm(new WeekProductionType(), $entity);
        $form->bind($request);

        $productPrices = $request->request->get('productPrices');
        
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            
            $i = 0;
            foreach($entity->getProductUnits() as $popu) {
                //remove product with no quantity
                if($popu->getQuantity() == 0) $entity->removeProductUnit($popu);
                else {
                    $productPrice = $em->getRepository('SmlePanBundle:ProductPrice')->find($productPrices[$i]);
                    $popu->setProductPrice($productPrice);
                    $popu->setWeekProduction($entity);
                    $em->persist($popu);
                }
                $i++;
            }
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('weekproduction_edit', array('id' => $entity->getId())));
        }

        return $this->redirect($this->generateUrl('weekproduction_new', array('date' => $entity->getDate()->format('Y-m-d'))));
    }

    /**
     * Creates a new WeekProduction entity via Ajax.
     *
     */
    public function ajaxCreateAction($date)
    {
        $request = $this->container->get('request');
//        if($request->isXmlHttpRequest())
//        {
            //return new Response('<span>'.$date.'</span>');
            $date = new \DateTime($date);
            
            $em = $this->getDoctrine()->getManager();
            $date->modify('+' .($request->get('jour')). ' Days');
            
            $entity  = $em->getRepository('SmlePanBundle:WeekProduction')->findOneBy(array('date' => $date, 'prevision' => false));

            if (!$entity) {
                $entity  = new WeekProduction();
                $entity->setDate($date);
                $entity->setPrevision(false);
            }
            
            $popu = $entity->getProductUnit($request->get('popu'));
            if (!is_object($popu)) {
                $pp = $em->getRepository('SmlePanBundle:ProductPrice')->find($request->get('popu'));
                $popu = new PanierOrderProductUnit();
                $popu->setWeekProduction($entity);
                $popu->setProductPrice($pp);
                $popu->setQuantity($request->get('qty'));
                $entity->addProductUnit($popu);
                $em->persist($entity);
            }
            else
            {
                $popu->setQuantity($request->get('qty'));
                $em->persist($popu);
            }
            
            $em->flush();
                
            return new Response('<span>'.$popu->getQuantity().'</span>');
//        }

        return new Response('problème...');
    }

    /**
     * Displays a form to edit an existing WeekProduction entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SmlePanBundle:WeekProduction')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find WeekProduction entity.');
        }

        // search for available other products (not in panierorder)
        $tpu = array();
        foreach($entity->getProductUnits() as $popu) $tpu[] = $popu->getProductPrice()->getId();
        $otherProductPrices = $em->getRepository('SmlePanBundle:ProductPrice')->findCurrents($entity->getDate(), implode(',', $tpu));
        
        foreach($otherProductPrices as $productPrice) {
                $panierOrderProductUnit = new PanierOrderProductUnit;
                $panierOrderProductUnit->setProductPrice($productPrice);
                $panierOrderProductUnit->setWeekProduction($entity);
                $entity->addProductUnit($panierOrderProductUnit);
        }
        
        $editForm = $this->createForm(new WeekProductionType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('SmlePanBundle:WeekProduction:edit.html.twig', array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Edits an existing WeekProduction entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SmlePanBundle:WeekProduction')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find WeekProduction entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm(new WeekProductionType(), $entity);
        $editForm->bind($request);

        if ($editForm->isValid()) {
            $i = 0;
            foreach($entity->getProductUnits() as $popu) {
                //remove product with no quantity
                if($popu->getQuantity() == 0) $entity->removeProductUnit($popu);
                else if(!$popu->getProductPrice()){
                    $productPrice = $em->getRepository('SmlePanBundle:ProductPrice')->find($productPrices[$i]);
                    $popu->setProductPrice($productPrice);
                    $popu->setWeekProduction($entity);
                    $em->persist($popu);
                }
                $i++;
            }
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('weekproduction_edit', array('id' => $id)));
        }

        return $this->render('SmlePanBundle:WeekProduction:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a WeekProduction entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('SmlePanBundle:WeekProduction')->find($id);

            if (!$entity) {

Resources/views/WeekProduction/dailyEdit.html.twig
{% extends 'SmlePanBundle::layout.html.twig' %}

{% block body %}

<div>
<h1>Production - Réalisations</h1>

<dl>
    <dt>Semaine :</dt>
    <dd>{{ entity.date|getWeek('full') }}</dd>
</dl>

<table id="panier_table" class="records_list" style="table-layout: fixed;">
    <tbody>
        <tr>
            <th>Produits disponibles</th>
            <th>Unité</th>
            <th>
                {% if is_granted("ROLE_ADMIN") %}<a href="{{ path('weekproduction_new', { 'date' : entity.date|date('Y-m-d') }) }}">{% endif %}
                Prévisions
                {% if is_granted("ROLE_ADMIN") %}</a>{% endif %}
            </th>
            {% for i in 1..7 %}
            <th>{{ (i%7)|getDay }}</th>
            {% endfor %}
            <th>Réalisé</th>
        </tr>
        {% for pu in entity.productUnits %}
        <tr id="{{ pu.productPrice.productUnit.product.ref }}" class="{{ pu.productPrice.productUnit.product.ref }}
            {% if pu.quantity == 0 %}hidden{% endif %}
            ">
            <td>
                <input type="hidden" name="productPrices[]" value="{{ pu.productPrice.id }}" />{{ pu.productPrice.productUnit.product.label }}</td>
            <td>{{ pu.productPrice.productUnit.unit.label }}</td>
            <td class="cell_number">{{ pu.quantity }}</td>
            {% for i in 1..7 %}
            <td class="cell_number cell_input" id="{{ loop.index0 }}_{{ pu.productPrice.id }}"><span>{% if tdp[pu.productPrice.id][i%7] is defined %}{{ tdp[pu.productPrice.id][i%7] }}{% endif %}</span></td>
            {% endfor %}
            <td class="cell_number total_column"></td>
        </tr>    
        {% endfor %}
        <tr>
            <td></td>
            <td>Total</td>
            <td id="price_total" class="cell_number">{{ entity.totalQuantities }}</td>
            {% for i in 1..7 %}
            <td class="cell_number total_row"></td>
            {% endfor %}
            <td class="cell_number total_row total_column"></td>
        </tr>
    </tbody>
</table>
  
<div id="command_block">
    Ajouter un produit disponible
    <select id="unused_products" size="1">
        <option value="0">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
    {% for pu in entity.productUnits %}
        <option class="{{ pu.productPrice.productUnit.product.ref }} {% if pu.quantity != 0 %}hidden{% endif %}" value="{{ pu.productPrice.productUnit.product.ref }}">
            {{ pu.productPrice.productUnit.product.label }}
        </option>
    {% endfor %}
    </select>
<!--
<div class="fright"><input type="button" value="Modifier" onclick="document.weekproduction_form.submit();"></div>
-->
</div>

</div>

{% endblock %}

{% block javascripts %}{{ parent() }}
    {% javascripts
        '@SmlePanBundle/Resources/public/js/jshashtable.js'
        '@SmlePanBundle/Resources/public/js/jquery.numberformatter.min.js'
    %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
<script type="text/javascript">
var dateRef;
$.ajustPrices = function() {
    //2- adjust the no fixed lines (fixed : value set manually)
    tmpTotal = 0;
    $('.iqty').each(function() {
        if(!$(this).hasClass('fixed')) {
            this.value = rt;
            $.adjustLine(this);
        }
        tmpTotal += eval(this.parentNode.nextSibling.innerHTML);
        return;
    });
    //3- some formatting
    $('#price_total').html(tmpTotal);
    $('.iqty').formatNumber({format:"#0.0", locale:"us"});
    $('.cell_number').formatNumber({format:"#0.00", locale:"us"});
    return;
}

$.adjustLine = function(iqty) {
    var next = $(iqty.parentNode).next();
    var weight_total = iqty.value;
    // Column price (PU * qty)
    next.html(weight_total * iqty.parentNode.previousSibling.innerHTML);
    return false;
}

$.toggleLock = function(img, lock) {
    if(lock && $(img).hasClass('lock')) return;
    var parent = $(img).parent();
    $(parent).children('img').toggleClass('hidden');
    $(parent).append(img);
    return;
}

$.clear = function(p) {
    var tr = $(p).parents('tr');
    var iqty = tr.find('.iqty');
    iqty.attr('value', 0);
    iqty.trigger('change');
    //$('.' + $(tr).attr('id')).toggleClass('hidden');
    return;
}

$.revert = function(elem) {
    $(elem).prev().toggleClass('hidden');
    $(elem).remove();
}

$.validate = function(elem) {
    if(!eval(elem.value)) return $.revert(elem);
    var params = elem.parentNode.id.split('_');
    $.ajax({
        type: "POST",
        url: {% if is_granted("ROLE_ADMIN") %}"{{ path('production_new', { 'date' : entity.date|date('Y-m-d') }) }}"{% else %}"{{ path('smle_pan_user_product_new', { 'user' : app.user.username, 'date' : entity.date|date('Y-m-d') }) }}"{% endif %},
        data: {
            'jour': params[0],
            'popu': params[1],
            'qty': elem.value
            },
        success: function(response){
            var td = $(elem).parent();
            $(td).html(response);
            $(td).parent('tr').next().children('td:eq(' + $(td).index() + ')').trigger('click');
        }
    }).fail(function() { alert("error"); });    
}

/*
$(document).keyup(function(event){
    event.preventDefault();
    var iqty = $('#iqty').get(0);
    if(event.which > 26 && event.which < 41){
        if(iqty) {
            var td = iqty.parentNode;
            switch(event.which){
                case 27: $(iqty).attr('value', $(iqty).prev().html());$.validate(iqty);break;
                case 37: $.validate(iqty);$(td).prev().trigger('click');break;
                case 38: $.validate(iqty);$(td).parent('tr').prev().children('td:eq(' + $(td).index() + ')').trigger('click');break;
                case 39: $.validate(iqty);$(td).next().trigger('click');break;
                case 40: $.validate(iqty);$(td).parent('tr').next().children('td:eq(' + $(td).index() + ')').trigger('click');break;
            }
        }
    }
    return;
}); 
*/

$(document).ready(function(){
    dateRef = '{{ entity.date|date('Y-m-d') }}';
/*
    $('.iqty').change(function(evt) {
        $(this).addClass('fixed');
        $.adjustLine(this);
        if(this.value == 0) {
            $('.' + this.parentNode.parentNode.id).toggleClass('hidden');
        }
        $.toggleLock($(this).next(), true)
        $.ajustPrices();
        return;
    }).focus(function(){
        lastField = this;
        $('#last_value').attr('value',this.value);
        this.select();
    });
*/
    //setting input elements
    $('.cell_input').click(function(){
        $('#iqty').remove();
        $(this).append('<input type="text" class="ffloat" id="iqty" value="' + $(this).children().first().html() + '" />');
        $(this).children().first().toggleClass('hidden');
        $('#iqty').blur(function(){
            $.validate(this);
        }).focus().keypress(function(event){
            var td = this.parentNode;
            switch(event.which){
                case 13: $.validate(this);break;
                //case 27: $(iqty).attr('value', $(iqty).prev().html());$.validate(iqty);break;
            }
            return;
        });
    });
    //clear button
    $('.cancel').click(function() {
        $.clear(this);
        $.ajustPrices();
        return;
    });
    //selector for products with no quantity
    $('#unused_products').change(function() {
        if(!this.value) return;
        $('.' + this.value).toggleClass('hidden');
        this.value = 0;
        return;
    });
    //$.ajustPrices();
    $('#command_block').width($('#panier_table').width());
});

</script>
{% endblock %}

Resources/views/WeekProduction/edit.html.twig
{% extends 'SmlePanBundle::layout.html.twig' %}

{% block body %}

<div>
<h1>Prévisions de Production</h1>

<dl>
    <dt>Semaine :</dt>
    <dd>{{ entity.date|getWeek('full') }}</dd>
</dl>

<form id="weekproduction_form" name="weekproduction_form" action="{{ path('weekproduction_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(form) }}>
    <table id="panier_table" class="records_list" style="table-layout: fixed;">
        <tbody>
            <tr>
                <th>Produits disponibles</th>
                <th>Unité</th>
                <th>Prix</th>
                <th>Quantité</th>
                <th>Prix Total</th>
            </tr>
            {% for pu in form.productUnits %}
            <tr id="{{ entity.productUnits[loop.index0].productPrice.productUnit.product.ref }}" class="{{ entity.productUnits[loop.index0].productPrice.productUnit.product.ref }}
                {% if pu.quantity.vars.value == 0 %}hidden{% endif %}
                ">
                <td>
                    {% image
                        '@SmlePanBundle/Resources/public/images/cancel.png'
                    %}
                        <img class="cancel" src='{{ asset_url }}' alt='effacer' height='11'/>
                    {% endimage %}
                    <input type="hidden" name="productPrices[]" value="{{ entity.productUnits[loop.index0].productPrice.id }}" />{{ entity.productUnits[loop.index0].productPrice.productUnit.product.label }}</td>
                <td>{{ entity.productUnits[loop.index0].productPrice.productUnit.unit.label }}</td>
                <td class="pu_price">{{ entity.productUnits[loop.index0].productPrice.price }}</td><td>{{ form_widget(pu.quantity, { 'attr': { 'class': 'ifloat iqty fixed', 'tabindex': loop.index } }) }}
                </td><td class="cell_number line_total">{{ entity.productUnits[loop.index0].productPrice.price * pu.quantity.vars.value }}</td>
            </tr>    
            {% endfor %}
            <tr>
                <td>
                </td>
                <td></td>
                <td></td>
                <td>Total</td>
                <td id="price_total" class="cell_number">0</td>
            </tr>
        </tbody>
    </table>
<div class="hidden">{{ form_rest(form) }}<input type="hidden" id="last_value" /></div>    
<div id="command_block">
    Ajouter un produit disponible
    <select id="unused_products" size="1">
        <option value="0">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</option>
    {% for pu in entity.productUnits %}
        <option class="{{ pu.productPrice.productUnit.product.ref }} {% if pu.quantity != 0 %}hidden{% endif %}" value="{{ pu.productPrice.productUnit.product.ref }}">
            {{ pu.productPrice.productUnit.product.label }}
        </option>
    {% endfor %}
    </select>
<div class="fright"><input type="button" value="Modifier" onclick="document.weekproduction_form.submit();"></div>
</div>
</form>

</div>

<br />

<div>
    <form action="{{ path('weekproduction_delete', { 'id': entity.id }) }}" method="post" class="inlined">
        {{ form_widget(delete_form) }}
        <button type="submit">Supprimer</button>
    </form>
    &nbsp;
</div>


{% endblock %}

{% block javascripts %}{{ parent() }}
    {% javascripts
        '@SmlePanBundle/Resources/public/js/jshashtable.js'
        '@SmlePanBundle/Resources/public/js/jquery.numberformatter.min.js'
    %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
<script type="text/javascript">
$.ajustPrices = function() {
    //2- adjust the no fixed lines (fixed : value set manually)
    tmpTotal = 0;
    $('.iqty').each(function() {
        if(!$(this).hasClass('fixed')) {
            this.value = rt;
            $.adjustLine(this);
        }
        tmpTotal += eval(this.parentNode.nextSibling.innerHTML);
        return;
    });
    //3- some formatting
    $('#price_total').html(tmpTotal);
    $('.iqty').formatNumber({format:"#0.0", locale:"us"});
    $('.cell_number').formatNumber({format:"#0.00", locale:"us"});
    return;
}

$.adjustLine = function(iqty) {
    var next = $(iqty.parentNode).next();
    var weight_total = iqty.value;
    // Column price (PU * qty)
    next.html(weight_total * iqty.parentNode.previousSibling.innerHTML);
    return false;
}

$.toggleLock = function(img, lock) {
    if(lock && $(img).hasClass('lock')) return;
    var parent = $(img).parent();
    $(parent).children('img').toggleClass('hidden');
    $(parent).append(img);
    return;
}

$.clear = function(p) {
    var tr = $(p).parents('tr');
    var iqty = tr.find('.iqty');
    iqty.attr('value', 0);
    iqty.trigger('change');
    //$('.' + $(tr).attr('id')).toggleClass('hidden');
    return;
}

$(document).ready(function(){
    $('.iqty').change(function(evt) {
        $(this).addClass('fixed');
        $.adjustLine(this);
        if(this.value == 0) {
            $('.' + this.parentNode.parentNode.id).toggleClass('hidden');
        }
        $.toggleLock($(this).next(), true)
        $.ajustPrices();
        return;
    }).focus(function(){
        lastField = this;
        $('#last_value').attr('value',this.value);
        this.select();
    });
    //clear button
    $('.cancel').click(function() {
        $.clear(this);
        $.ajustPrices();
        return;
    });
    //selector for products with no quantity
    $('#unused_products').change(function() {
        if(!this.value) return;
        $('.' + this.value).toggleClass('hidden');
        this.value = 0;
        return;
    });
    $.ajustPrices();
    $('#command_block').width($('#panier_table').width());
});

</script>
{% endblock %}

Resources/views/WeekProduction/index.html.twig
<h1>WeekProduction list</h1>

<table class="records_list">
    <thead>
        <tr>
            <th>Id</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for entity in entities %}
        <tr>
            <td><a href="{{ path('weekproduction_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
            <td>{% if entity.date %}{{ entity.date|date('Y-m-d H:i:s') }}{% endif %}</td>
            <td>
                <ul>
                    <li>
                        <a href="{{ path('weekproduction_show', { 'id': entity.id }) }}">show</a>
                    </li>
                    <li>
                        <a href="{{ path('weekproduction_edit', { 'id': entity.id }) }}">edit</a>
                    </li>
                </ul>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<ul>
    <li>
        <a href="{{ path('weekproduction_new') }}">
            Create a new entry
        </a>
    </li>
</ul>

Resources/views/WeekProduction/show.html.twig
<h1>WeekProduction</h1>

<table class="record_properties">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ entity.date|date('Y-m-d H:i:s') }}</td>
        </tr>
    </tbody>
</table>

<ul class="record_actions">
    <li>
        <a href="{{ path('weekproduction') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('weekproduction_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>
        <form action="{{ path('weekproduction_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>